import ISRDF.Rdf
import Mathlib.Tactic.Set

/-!
# Implication-Space Semantics for RDF — Part 2: the semantics and the recovery results

Roles are handled through generating sets and `RSR`, as Definition 6 licenses; Lemma 2
(Reduction, `reduction`) is what makes checking entailment on a generating set legitimate,
and `RSR_adj`/`RSR_union` show the operations respect the equivalence "same `RSR`".
The ground contents of Definition 10 are entered by their generating pairs (as in the
sentence after Definition 10); Definition 11 is built from them with the generic
power-symjunction and adjunction, and Lemma 3 (Shapes) is proved from that.
-/

set_option autoImplicit false

namespace ISRDF

variable {Iri Lit Bn : Type} {V : Set Iri}

/-! ## §3.1  Implication-space semantics -/

/-- Definition 5: the implication space `S = P(B) × P(B)` over a set of bearers. -/
abbrev ISpace (Br : Type) := Set Br × Set Br

section Roles
variable {Br : Type}

/-- `⟨Γ ∪ x, Δ ∪ y⟩`. -/
def ISpace.add (p q : ISpace Br) : ISpace Br := (p.1 ∪ q.1, p.2 ∪ q.2)

theorem ISpace.add_assoc (p q r : ISpace Br) : (p.add q).add r = p.add (q.add r) := by
  simp [ISpace.add, Set.union_assoc]

@[simp] theorem ISpace.add_empty (p : ISpace Br) : p.add (∅, ∅) = p := by
  simp [ISpace.add]

@[simp] theorem ISpace.empty_add (p : ISpace Br) : ISpace.add (∅, ∅) p = p := by
  simp [ISpace.add]

/-- Definition 6: range of subjunctive robustness of a set of candidate implications. -/
def RSR (I H : Set (ISpace Br)) : Set (ISpace Br) := {q | ∀ p ∈ H, p.add q ∈ I}

/-- Definition 6: the implicational role generated by `H`, as the class of all generating
sets with the same `RSR`. -/
def Role (I H : Set (ISpace Br)) : Set (Set (ISpace Br)) := {x | RSR I H = RSR I x}

theorem mem_Role_self (I H : Set (ISpace Br)) : H ∈ Role I H := rfl

theorem empty_mem_RSR_iff (I X : Set (ISpace Br)) : ((∅, ∅) : ISpace Br) ∈ RSR I X ↔ X ⊆ I := by
  simp only [RSR, Set.mem_ofPred_eq, ISpace.add_empty]
  rfl

/-- **Lemma 2 (Reduction).** `⋃ R(F) ⊆ I` iff `F ⊆ I`. -/
theorem reduction (I F : Set (ISpace Br)) : ⋃₀ Role I F ⊆ I ↔ F ⊆ I := by
  constructor
  · intro h p hp
    exact h (Set.mem_sUnion.2 ⟨F, mem_Role_self I F, hp⟩)
  · intro hF x hx
    obtain ⟨X, hX, hxX⟩ := Set.mem_sUnion.1 hx
    have : ((∅, ∅) : ISpace Br) ∈ RSR I X := by
      rw [← hX]; exact (empty_mem_RSR_iff I F).2 hF
    exact (empty_mem_RSR_iff I X).1 this hxX

/-- Adjunction on generating sets (Definition 6). -/
def adj (H J : Set (ISpace Br)) : Set (ISpace Br) := {p | ∃ a ∈ H, ∃ b ∈ J, p = a.add b}

/-- Adjunction of a family of generating sets indexed by `x`: choose one pair per member
and union coordinatewise. -/
def adjFam {ι : Type} (x : Set ι) (g : ι → Set (ISpace Br)) : Set (ISpace Br) :=
  {p | ∃ f : ι → ISpace Br, (∀ i ∈ x, f i ∈ g i) ∧ p = (⋃ i ∈ x, (f i).1, ⋃ i ∈ x, (f i).2)}

/-- Power-symjunction `∇X = ⊓{⊔x | ∅ ≠ x ⊆ X}` on generating sets (symjunction is union). -/
def powSymj {ι : Type} (X : Set ι) (g : ι → Set (ISpace Br)) : Set (ISpace Br) :=
  ⋃ x ∈ {x : Set ι | x ⊆ X ∧ x.Nonempty}, adjFam x g

/-- `RSR` of an adjunction depends only on the `RSR`s of the arguments. -/
theorem RSR_adj (I H J : Set (ISpace Br)) :
    RSR I (adj H J) = {q | ∀ b ∈ J, b.add q ∈ RSR I H} := by
  ext q
  simp only [RSR, adj, Set.mem_ofPred_eq]
  constructor
  · intro h b hb a ha
    rw [← ISpace.add_assoc]
    exact h _ ⟨a, ha, b, hb, rfl⟩
  · rintro h _ ⟨a, ha, b, hb, rfl⟩
    rw [ISpace.add_assoc]
    exact h b hb a ha

/-- `RSR` of a symjunction is the intersection of the `RSR`s. -/
theorem RSR_union (I H J : Set (ISpace Br)) : RSR I (H ∪ J) = RSR I H ∩ RSR I J := by
  ext q
  simp only [RSR, Set.mem_ofPred_eq, Set.mem_inter_iff, Set.mem_union]
  constructor
  · intro h; exact ⟨fun p hp => h p (Or.inl hp), fun p hp => h p (Or.inr hp)⟩
  · rintro ⟨h₁, h₂⟩ p (hp | hp)
    · exact h₁ p hp
    · exact h₂ p hp

theorem adj_congr {I H H' J : Set (ISpace Br)} (h : RSR I H = RSR I H') :
    RSR I (adj H J) = RSR I (adj H' J) := by
  rw [RSR_adj, RSR_adj, h]

theorem adjFam_singletons {ι : Type} (x : Set ι) (A B : ι → Set Br) :
    adjFam x (fun i => {(A i, B i)}) = {(⋃ i ∈ x, A i, ⋃ i ∈ x, B i)} := by
  ext p
  simp only [adjFam, Set.mem_ofPred_eq, Set.mem_singleton_iff]
  constructor
  · rintro ⟨f, hf, rfl⟩
    have h1 : ∀ i ∈ x, (f i).1 = A i := fun i hi => by rw [hf i hi]
    have h2 : ∀ i ∈ x, (f i).2 = B i := fun i hi => by rw [hf i hi]
    congr 1
    · exact Set.iUnion₂_congr h1
    · exact Set.iUnion₂_congr h2
  · rintro rfl
    exact ⟨fun i => (A i, B i), fun _ _ => rfl, rfl⟩

theorem adjFam_empty {ι : Type} (g : ι → Set (ISpace Br)) :
    adjFam (∅ : Set ι) g = {(∅, ∅)} := by
  ext p
  simp [adjFam]

theorem mem_adj_singleton_right {H : Set (ISpace Br)} {p : ISpace Br} :
    p ∈ adj H {(∅, ∅)} ↔ p ∈ H := by
  simp only [adj, Set.mem_ofPred_eq, Set.mem_singleton_iff, exists_eq_left, ISpace.add_empty]
  exact ⟨fun ⟨a, ha, h⟩ => h ▸ ha, fun h => ⟨p, h, rfl⟩⟩

/-- Definition 7: content entailment, given generating sets of `⊔ gᵢ⁺` and `⊔ dⱼ⁻`. -/
def CEnt (I Gpos Dneg : Set (ISpace Br)) : Prop := ⋃₀ Role I (adj Gpos Dneg) ⊆ I

/-- By Lemma 2, content entailment can be checked on the generating set. -/
theorem cEnt_iff (I Gpos Dneg : Set (ISpace Br)) : CEnt I Gpos Dneg ↔ adj Gpos Dneg ⊆ I :=
  reduction I _

/-- Definition 8: the canonical frame. -/
def IC (Br : Type) : Set (ISpace Br) := {p | (p.1 ∩ p.2).Nonempty}
end Roles

/-! ## §3.2  Contents of RDF graphs -/

/-- An implication-space model for RDF (Definitions 7 and 9): a set of objects, a set of good
implications over bearers `T⟨s,p,o⟩`, and an interpretation of names. (We interpret all
terms; only ground triples are ever sent to bearers.) -/
structure Model (Iri Lit Bn : Type) where
  Obj : Type
  I : Set (ISpace (Triple Obj))
  interp : Term Iri Lit Bn → Obj

/-- Instance mappings `bnodes(H) → N` (Definition 11), as total maps. -/
def IMap (N : Set (Term Iri Lit Bn)) (H : Graph Iri Lit Bn) : Set (Bn → Term Iri Lit Bn) :=
  {μ | ∀ b ∈ H.bnodes, μ b ∈ N}

/-- The lexicon over `N`: ground triples all of whose terms lie in `N` (Definition 13). -/
def Lex (N : Set (Term Iri Lit Bn)) : Graph Iri Lit Bn := {t | ∀ x ∈ t.terms, x ∈ N}

theorem Graph.subset_lex_iff {N : Set (Term Iri Lit Bn)} (G : Graph Iri Lit Bn) :
    G ⊆ Lex N ↔ G.Over N := Iff.rfl

theorem Graph.inst_subset_lex {N : Set (Term Iri Lit Bn)} {G : Graph Iri Lit Bn}
    (hG : G.names ⊆ N) {ν} (hν : ν ∈ IMap N G) : G.inst ν ⊆ Lex N := by
  intro t ht x hx
  have : x ∈ (G.inst ν).terms := ⟨t, ht, hx⟩
  rcases G.terms_inst_subset ν this with h | ⟨b, hb, rfl⟩
  · exact hG h
  · exact hν b hb

namespace Model
variable (M : Model Iri Lit Bn)

/-- The bearer map `B` (Definition 9). -/
def br (t : Triple (Term Iri Lit Bn)) : Triple M.Obj := t.map M.interp

/-- `B(G)`. -/
def brG (G : Graph Iri Lit Bn) : Set (Triple M.Obj) := M.br '' G

theorem brG_mono {G H : Graph Iri Lit Bn} (h : G ⊆ H) : M.brG G ⊆ M.brG H := Set.image_mono h

/-- Content entailment between *sets of atomic sentences* (Definition 7 with the atomic
clause): `⊔ R⁺(B t)` over `Γ` against `⊔ R⁻(B t)` over `Δ`. This is the notion fitness
(Definition 13) quantifies over. -/
def SentEnt (Γ Δ : Graph Iri Lit Bn) : Prop :=
  CEnt M.I (adjFam Γ fun t => {({M.br t}, ∅)}) (adjFam Δ fun t => {(∅, {M.br t})})

theorem biUnion_singleton_br (G : Graph Iri Lit Bn) : (⋃ t ∈ G, {M.br t}) = M.brG G := by
  ext b; simp [brG, eq_comm]

/-- **Proposition 1 (Positional criterion).** -/
theorem positional (Γ Δ : Graph Iri Lit Bn) : M.SentEnt Γ Δ ↔ (M.brG Γ, M.brG Δ) ∈ M.I := by
  unfold SentEnt
  rw [cEnt_iff, adjFam_singletons, adjFam_singletons]
  simp only [Set.iUnion_empty, biUnion_singleton_br]
  constructor
  · intro h
    have := h ⟨_, rfl, _, rfl, rfl⟩
    simpa [ISpace.add] using this
  · rintro h _ ⟨a, rfl, b, rfl, rfl⟩
    simpa [ISpace.add] using h

/-- Definition 10: the generating pair of `⟦G⟧⁺` for ground `G`. -/
def groundPos (G : Graph Iri Lit Bn) : Set (ISpace (Triple M.Obj)) := {(M.brG G, ∅)}

/-- Definition 10: the generating pairs of `⟦G⟧⁻` for ground `G`. -/
def groundNeg (G : Graph Iri Lit Bn) : Set (ISpace (Triple M.Obj)) :=
  {p | ∃ S, S.Nonempty ∧ S ⊆ M.brG G ∧ p = (∅, S)}

/-- Definition 11: `⟦H⟧⁺ = ∇{⟦μ(H)⟧⁺ | μ}`, on generating sets. -/
def pos (N : Set (Term Iri Lit Bn)) (G : Graph Iri Lit Bn) : Set (ISpace (Triple M.Obj)) :=
  powSymj (IMap N G) fun ν => M.groundPos (G.inst ν)

/-- Definition 11: `⟦H⟧⁻ = ⊔{⟦μ(H)⟧⁻ | μ}`, on generating sets. -/
def neg (N : Set (Term Iri Lit Bn)) (H : Graph Iri Lit Bn) : Set (ISpace (Triple M.Obj)) :=
  adjFam (IMap N H) fun μ => M.groundNeg (H.inst μ)

/-- `⟦G⟧ |∼ ⟦H⟧` in `M`, for graphs. -/
def GEnt (N : Set (Term Iri Lit Bn)) (G H : Graph Iri Lit Bn) : Prop :=
  CEnt M.I (M.pos N G) (M.neg N H)

/-- `⟦G⟧ |∼ ∅` in `M`: the adjunction over the empty succedent family is generated by
`⟨∅, ∅⟩` (Proposition 2). -/
def Incoherent (N : Set (Term Iri Lit Bn)) (G : Graph Iri Lit Bn) : Prop :=
  CEnt M.I (M.pos N G) {(∅, ∅)}

/-- **Lemma 3 (Shapes)**, positive half. -/
theorem mem_pos_iff {N} {G : Graph Iri Lit Bn} {p} :
    p ∈ M.pos N G ↔
      ∃ x ⊆ IMap N G, x.Nonempty ∧ p = (⋃ ν ∈ x, M.brG (G.inst ν), ∅) := by
  simp only [pos, powSymj, groundPos, Set.mem_iUnion, Set.mem_ofPred_eq, exists_prop]
  constructor
  · rintro ⟨x, ⟨hx, hne⟩, hp⟩
    rw [adjFam_singletons, Set.mem_singleton_iff] at hp
    refine ⟨x, hx, hne, ?_⟩
    rw [hp]; simp
  · rintro ⟨x, hx, hne, rfl⟩
    refine ⟨x, ⟨hx, hne⟩, ?_⟩
    rw [adjFam_singletons, Set.mem_singleton_iff]
    simp

/-- **Lemma 3 (Shapes)**, negative half. -/
theorem mem_neg_iff {N} {H : Graph Iri Lit Bn} {p} :
    p ∈ M.neg N H ↔
      ∃ S : (Bn → Term Iri Lit Bn) → Set (Triple M.Obj),
        (∀ μ ∈ IMap N H, (S μ).Nonempty ∧ S μ ⊆ M.brG (H.inst μ)) ∧
        p = (∅, ⋃ μ ∈ IMap N H, S μ) := by
  simp only [neg, adjFam, groundNeg, Set.mem_ofPred_eq]
  constructor
  · rintro ⟨f, hf, rfl⟩
    refine ⟨fun μ => (f μ).2, fun μ hμ => ?_, ?_⟩
    · obtain ⟨S, hS, hSsub, hfμ⟩ := hf μ hμ
      show (f μ).2.Nonempty ∧ (f μ).2 ⊆ _
      rw [hfμ]; exact ⟨hS, hSsub⟩
    · congr 1
      apply Set.eq_empty_of_subset_empty
      intro b hb
      simp only [Set.mem_iUnion, exists_prop] at hb
      obtain ⟨μ, hμ, hb⟩ := hb
      obtain ⟨S, -, -, hfμ⟩ := hf μ hμ
      rw [hfμ] at hb
      exact hb
  · rintro ⟨S, hS, rfl⟩
    exact ⟨fun μ => (∅, S μ), fun μ hμ => ⟨S μ, (hS μ hμ).1, (hS μ hμ).2, rfl⟩, by simp⟩

/-- The pairs of `⟦G⟧ |∼ ⟦H⟧` (the paragraph after Lemma 3). -/
theorem mem_pairs_iff {N} {G H : Graph Iri Lit Bn} {p} :
    p ∈ adj (M.pos N G) (M.neg N H) ↔
      ∃ x ⊆ IMap N G, x.Nonempty ∧
      ∃ S : (Bn → Term Iri Lit Bn) → Set (Triple M.Obj),
        (∀ μ ∈ IMap N H, (S μ).Nonempty ∧ S μ ⊆ M.brG (H.inst μ)) ∧
        p = (⋃ ν ∈ x, M.brG (G.inst ν), ⋃ μ ∈ IMap N H, S μ) := by
  simp only [adj, Set.mem_ofPred_eq]
  constructor
  · rintro ⟨a, ha, b, hb, rfl⟩
    obtain ⟨x, hx, hne, rfl⟩ := M.mem_pos_iff.1 ha
    obtain ⟨S, hS, rfl⟩ := M.mem_neg_iff.1 hb
    exact ⟨x, hx, hne, S, hS, by simp [ISpace.add]⟩
  · rintro ⟨x, hx, hne, S, hS, rfl⟩
    refine ⟨_, M.mem_pos_iff.2 ⟨x, hx, hne, rfl⟩, _, M.mem_neg_iff.2 ⟨S, hS, rfl⟩, ?_⟩
    simp [ISpace.add]

theorem gEnt_iff {N} {G H : Graph Iri Lit Bn} :
    M.GEnt N G H ↔ ∀ (x : Set (Bn → Term Iri Lit Bn)), x ⊆ IMap N G → x.Nonempty →
      ∀ S : (Bn → Term Iri Lit Bn) → Set (Triple M.Obj),
        (∀ μ ∈ IMap N H, (S μ).Nonempty ∧ S μ ⊆ M.brG (H.inst μ)) →
        (⋃ ν ∈ x, M.brG (G.inst ν), ⋃ μ ∈ IMap N H, S μ) ∈ M.I := by
  unfold GEnt
  rw [cEnt_iff]
  constructor
  · intro h x hx hne S hS
    exact h (M.mem_pairs_iff.2 ⟨x, hx, hne, S, hS, rfl⟩)
  · intro h p hp
    obtain ⟨x, hx, hne, S, hS, rfl⟩ := M.mem_pairs_iff.1 hp
    exact h x hx hne S hS

theorem incoherent_iff {N} {G : Graph Iri Lit Bn} :
    M.Incoherent N G ↔ ∀ (x : Set (Bn → Term Iri Lit Bn)), x ⊆ IMap N G → x.Nonempty →
      (⋃ ν ∈ x, M.brG (G.inst ν), (∅ : Set (Triple M.Obj))) ∈ M.I := by
  unfold Incoherent
  rw [cEnt_iff]
  constructor
  · intro h x hx hne
    exact h (mem_adj_singleton_right.2 (M.mem_pos_iff.2 ⟨x, hx, hne, rfl⟩))
  · intro h p hp
    obtain ⟨x, hx, hne, rfl⟩ := M.mem_pos_iff.1 (mem_adj_singleton_right.1 hp)
    exact h x hx hne
end Model

/-! ## §3.3  Bases, frames and Herbrand models -/

/-- Definition 13: a base over `N`, with Containment on the lexicon. -/
structure Base (N : Set (Term Iri Lit Bn)) where
  rel : Graph Iri Lit Bn → Graph Iri Lit Bn → Prop
  containment : ∀ Γ Δ, Γ ⊆ Lex N → Δ ⊆ Lex N → (Γ ∩ Δ).Nonempty → rel Γ Δ

variable {N : Set (Term Iri Lit Bn)}

/-- Definition 13: `M` is fit for `B` iff every base implication holds in `M`. -/
def Model.Fit (M : Model Iri Lit Bn) (B : Base N) : Prop :=
  ∀ Γ Δ, Γ ⊆ Lex N → Δ ⊆ Lex N → B.rel Γ Δ → M.SentEnt Γ Δ

/-- Definition 14: the frame induced by a base (bearers are the ground triples themselves,
since the Herbrand bearer map is the identity). -/
def Base.frame (B : Base N) : Set (ISpace (Triple (Term Iri Lit Bn))) :=
  IC _ ∪ {p | ∃ Γ Δ, Γ ⊆ Lex N ∧ Δ ⊆ Lex N ∧ B.rel Γ Δ ∧ p = (Γ, Δ)}

/-- Definition 15: the Herbrand model of a base. -/
abbrev Base.herbrand (B : Base N) : Model Iri Lit Bn :=
  ⟨Term Iri Lit Bn, B.frame, fun x => x⟩

@[simp] theorem Base.herbrand_br (B : Base N) (t) : B.herbrand.br t = t := by
  simp [Model.br, Base.herbrand]

@[simp] theorem Base.herbrand_brG (B : Base N) (G : Graph Iri Lit Bn) : B.herbrand.brG G = G := by
  ext t
  constructor
  · rintro ⟨u, hu, rfl⟩; rw [Base.herbrand_br]; exact hu
  · intro h; exact ⟨t, h, Base.herbrand_br B t⟩

@[simp] theorem Base.herbrand_I (B : Base N) : B.herbrand.I = B.frame := rfl

theorem Base.mem_frame_of_rel (B : Base N) {Γ Δ : Graph Iri Lit Bn} (hΓ : Γ ⊆ Lex N)
    (hΔ : Δ ⊆ Lex N) (h : B.rel Γ Δ) : (Γ, Δ) ∈ B.frame :=
  Or.inr ⟨Γ, Δ, hΓ, hΔ, h, rfl⟩

theorem Base.rel_of_mem_frame (B : Base N) {Γ Δ : Graph Iri Lit Bn} (hΓ : Γ ⊆ Lex N)
    (hΔ : Δ ⊆ Lex N) (h : (Γ, Δ) ∈ B.frame) : B.rel Γ Δ := by
  rcases h with h | ⟨Γ', Δ', -, -, hr, heq⟩
  · exact B.containment Γ Δ hΓ hΔ h
  · obtain ⟨rfl, rfl⟩ := Prod.mk.inj heq
    exact hr

/-- The Herbrand model is fit for its base. -/
theorem Base.herbrand_fit (B : Base N) : B.herbrand.Fit B := by
  intro Γ Δ hΓ hΔ h
  rw [Model.positional, Base.herbrand_brG, Base.herbrand_brG]
  exact B.mem_frame_of_rel hΓ hΔ h

/-- The canonical RDF base `B_C`: Containment alone. -/
def canonicalBase (N : Set (Term Iri Lit Bn)) : Base N :=
  ⟨fun Γ Δ => (Γ ∩ Δ).Nonempty, fun _ _ _ _ h => h⟩

/-- The base `B_R` specified by a regime (Definition 13). -/
def Regime.base (R : Regime Iri Lit Bn V) (N : Set (Term Iri Lit Bn)) : Base N where
  rel Γ Δ := R.Inconsistent Γ ∨ (Δ ∩ R.clPos Γ).Nonempty
  containment := fun Γ _ _ _ ⟨t, ht, ht'⟩ => Or.inr ⟨t, ht', R.subset_clPos Γ ht⟩

/-- The empty regime's base is the canonical base. -/
theorem emptyRegime_base_rel (N : Set (Term Iri Lit Bn)) (Γ Δ : Graph Iri Lit Bn) :
    ((emptyRegime Iri Lit Bn V).base N).rel Γ Δ ↔ (canonicalBase N).rel Γ Δ := by
  show (_ ∨ (Δ ∩ _).Nonempty) ↔ (Γ ∩ Δ).Nonempty
  rw [emptyRegime_clPos, Set.inter_comm]
  constructor
  · rintro (h | h)
    · exact (emptyRegime_not_inconsistent V Γ h).elim
    · exact h
  · exact fun h => Or.inr h

/-! `B_R` is structural (the remarks after Definition 13): monotone, closed under Cut,
explosive. -/
section Structural
variable (R : Regime Iri Lit Bn V)

theorem Regime.base_mono_left {Γ Γ' Δ : Graph Iri Lit Bn} (h : Γ ⊆ Γ')
    (hr : (R.base N).rel Γ Δ) : (R.base N).rel Γ' Δ := by
  rcases hr with hi | ⟨t, ht, hc⟩
  · exact Or.inl (R.inconsistent_mono h hi)
  · exact Or.inr ⟨t, ht, R.clPos_mono h hc⟩

theorem Regime.base_mono_right {Γ Δ Δ' : Graph Iri Lit Bn} (h : Δ ⊆ Δ')
    (hr : (R.base N).rel Γ Δ) : (R.base N).rel Γ Δ' := by
  rcases hr with hi | ⟨t, ht, hc⟩
  · exact Or.inl hi
  · exact Or.inr ⟨t, h ht, hc⟩

theorem Regime.base_explosive {Γ : Graph Iri Lit Bn} (h : R.Inconsistent Γ) (Δ) :
    (R.base N).rel Γ Δ := Or.inl h

theorem Regime.base_cut {Γ Δ : Graph Iri Lit Bn} {t}
    (h₁ : (R.base N).rel Γ (Δ ∪ {t})) (h₂ : (R.base N).rel (Γ ∪ {t}) Δ) : (R.base N).rel Γ Δ := by
  rcases h₁ with hi | ⟨d, hd, hdc⟩
  · exact Or.inl hi
  · rcases hd with hd | hd
    · exact Or.inr ⟨d, hd, hdc⟩
    · rw [Set.mem_singleton_iff] at hd
      subst hd
      have hsub : Γ ∪ {d} ⊆ R.clPos Γ := by
        intro y hy
        rcases hy with hy | hy
        · exact R.subset_clPos Γ hy
        · rw [Set.mem_singleton_iff] at hy; subst hy; exact hdc
      rcases h₂ with hi | ⟨e, he, hec⟩
      · exact Or.inl (R.cl_clPos (R.cl_mono hsub hi))
      · exact Or.inr ⟨e, he, R.cl_clPos (R.cl_mono hsub hec)⟩
end Structural

/-! ## §3.4  Recovery -/

/-- Implication in the set of models fit for `B` (Definition 7, last clause). -/
def FitEnt (B : Base N) (G H : Graph Iri Lit Bn) : Prop :=
  ∀ M : Model Iri Lit Bn, M.Fit B → M.GEnt N G H

/-- **Theorem 1 (Recovery).** For graphs `G, H` whose names lie in `N`, implication in the
fit models coincides with implication in the Herbrand model. -/
theorem recovery (B : Base N) {G H : Graph Iri Lit Bn} (hG : G.names ⊆ N) (hH : H.names ⊆ N) :
    FitEnt B G H ↔ B.herbrand.GEnt N G H := by
  constructor
  · intro h
    exact h _ B.herbrand_fit
  · intro hHerb M hM
    rw [Model.gEnt_iff]
    intro x hx hne S hS
    -- the ground graphs Γ and Δ of the proof
    set Γ : Graph Iri Lit Bn := ⋃ ν ∈ x, G.inst ν with hΓdef
    set Δ : Graph Iri Lit Bn := ⋃ μ ∈ IMap N H, {t ∈ H.inst μ | M.br t ∈ S μ} with hΔdef
    have hΓ : Γ ⊆ Lex N := by
      intro t ht
      simp only [hΓdef, Set.mem_iUnion, exists_prop] at ht
      obtain ⟨ν, hν, ht⟩ := ht
      exact Graph.inst_subset_lex hG (hx hν) ht
    have hΔ : Δ ⊆ Lex N := by
      intro t ht
      simp only [hΔdef, Set.mem_iUnion, exists_prop, Set.mem_ofPred_eq] at ht
      obtain ⟨μ, hμ, ht, -⟩ := ht
      exact Graph.inst_subset_lex hH hμ ht
    -- the corresponding pair holds in the Herbrand model
    have hpair : (Γ, Δ) ∈ B.frame := by
      have := (B.herbrand.gEnt_iff).1 hHerb x hx hne (fun μ => Δ ∩ H.inst μ) (by
        intro μ hμ
        rw [Base.herbrand_brG]
        refine ⟨?_, Set.inter_subset_right⟩
        obtain ⟨b, hb⟩ := (hS μ hμ).1
        obtain ⟨t, ht, rfl⟩ := (hS μ hμ).2 hb
        refine ⟨t, ?_, ht⟩
        rw [hΔdef]
        exact Set.mem_biUnion hμ ⟨ht, hb⟩)
      simp only [Base.herbrand_brG] at this
      have hΔeq : (⋃ μ ∈ IMap N H, Δ ∩ H.inst μ) = Δ := by
        apply Set.Subset.antisymm
        · intro t ht
          simp only [Set.mem_iUnion, exists_prop] at ht
          obtain ⟨μ, -, ht, -⟩ := ht
          exact ht
        · intro t ht
          have ht' := ht
          simp only [hΔdef, Set.mem_iUnion, exists_prop, Set.mem_ofPred_eq] at ht'
          obtain ⟨μ, hμ, htμ, -⟩ := ht'
          exact Set.mem_biUnion hμ ⟨ht, htμ⟩
      rw [hΔeq] at this
      exact this
    have hrel : B.rel Γ Δ := B.rel_of_mem_frame hΓ hΔ hpair
    have hM' := (M.positional Γ Δ).1 (hM Γ Δ hΓ hΔ hrel)
    convert hM' using 2
    · simp only [hΓdef, Model.brG, Set.image_iUnion₂]
    · simp only [hΔdef, Model.brG, Set.image_iUnion₂]
      apply Set.iUnion₂_congr
      intro μ hμ
      apply Set.Subset.antisymm
      · intro b hb
        obtain ⟨t, ht, rfl⟩ := (hS μ hμ).2 hb
        exact ⟨t, ⟨ht, hb⟩, rfl⟩
      · rintro _ ⟨t, ⟨-, hb⟩, rfl⟩; exact hb

/-! ## §3.5  Closure regimes -/

/-- Definition 12: `N` is admissible for `G`, `H` and a regime over `V`. -/
structure Admissible (N : Set (Term Iri Lit Bn)) (G H : Graph Iri Lit Bn) (V : Set Iri) : Prop where
  names : ∀ x ∈ N, Term.IsName x
  hG : G.names ⊆ N
  hH : H.names ⊆ N
  hV : ∀ v ∈ V, Term.iri v ∈ N
  skolem : ∃ sk : Bn → Iri, Set.InjOn sk G.bnodes ∧ ∀ b ∈ G.bnodes,
    Term.iri (sk b) ∈ N ∧ Term.iri (sk b) ∉ G.names ∪ H.names ∪ ((fun v => Term.iri v) '' V)

section Skolem
open Classical

/-- The map `σ` of Lemma 5: undo the Skolem IRIs on `S`, fix everything else. -/
noncomputable def skolemInv (sk : Bn → Iri) (S : Set Bn) (x : Term Iri Lit Bn) : Term Iri Lit Bn :=
  if h : ∃ b ∈ S, x = Term.iri (sk b) then Term.bnode h.choose else x

theorem skolemInv_of_not {sk : Bn → Iri} {S : Set Bn} {x : Term Iri Lit Bn}
    (h : ¬ ∃ b ∈ S, x = Term.iri (sk b)) : skolemInv sk S x = x := by
  simp [skolemInv, h]

theorem skolemInv_iri {sk : Bn → Iri} {S : Set Bn} (hinj : Set.InjOn sk S) {b : Bn} (hb : b ∈ S) :
    skolemInv sk S (Term.iri (sk b) : Term Iri Lit Bn) = Term.bnode b := by
  have h : ∃ b' ∈ S, Term.iri (sk b) = (Term.iri (sk b') : Term Iri Lit Bn) := ⟨b, hb, rfl⟩
  simp only [skolemInv, h, dite_true]
  congr 1
  have hc := h.choose_spec
  exact (hinj hc.1 hb (Term.iri.inj hc.2).symm)

theorem skolemInv_bnode (sk : Bn → Iri) (S : Set Bn) (b : Bn) :
    skolemInv sk S (Term.bnode b : Term Iri Lit Bn) = Term.bnode b :=
  skolemInv_of_not (by rintro ⟨_, _, h⟩; cases h)

theorem skolemInv_lit (sk : Bn → Iri) (S : Set Bn) (l : Lit) :
    skolemInv sk S (Term.lit l : Term Iri Lit Bn) = Term.lit l :=
  skolemInv_of_not (by rintro ⟨_, _, h⟩; cases h)

/-- **Lemma 5 (Skolemization)**, packaged: from an admissible `N` we get `ν_sk` and `σ`
with the stated properties. -/
theorem skolemization {G H : Graph Iri Lit Bn} (hA : Admissible N G H V) :
    ∃ (νsk : Bn → Term Iri Lit Bn) (σ : Term Iri Lit Bn → Term Iri Lit Bn),
      νsk ∈ IMap N G ∧ FixesLV V σ ∧ Graph.mapT σ (G.inst νsk) = G ∧
      (∀ t ∈ H, ∀ x ∈ t.terms, σ x = x) := by
  obtain ⟨sk, hinj, hsk⟩ := hA.skolem
  refine ⟨fun b => Term.iri (sk b), skolemInv sk G.bnodes, fun b hb => (hsk b hb).1, ?_, ?_, ?_⟩
  · refine ⟨fun l => skolemInv_lit _ _ _, fun v hv => skolemInv_of_not ?_⟩
    rintro ⟨b, hb, h⟩
    exact (hsk b hb).2 (Or.inr ⟨v, hv, h⟩)
  · rw [Graph.inst, Graph.mapT_mapT]
    apply Graph.mapT_eq_self
    intro t ht x hx
    cases x with
    | bnode b =>
      simp only [Function.comp, Term.subst_bnode]
      exact skolemInv_iri hinj ⟨t, ht, hx⟩
    | iri a =>
      simp only [Function.comp, Term.subst_iri]
      apply skolemInv_of_not
      rintro ⟨b, hb, h⟩
      exact (hsk b hb).2 (Or.inl (Or.inl ⟨trivial, t, ht, h ▸ hx⟩))
    | lit a =>
      simp only [Function.comp, Term.subst_lit]
      exact skolemInv_lit _ _ _
  · intro t ht x hx
    cases x with
    | bnode b => exact skolemInv_bnode _ _ _
    | lit a => exact skolemInv_lit _ _ _
    | iri a =>
      apply skolemInv_of_not
      rintro ⟨b, hb, h⟩
      exact (hsk b hb).2 (Or.inl (Or.inr ⟨trivial, t, ht, h ▸ hx⟩))
end Skolem

/-- `σ(μ(H)) = (σ ∘ μ)(H)` when `σ` fixes the names of `H`. -/
theorem Graph.mapT_inst_of_fixes {H : Graph Iri Lit Bn} {σ : Term Iri Lit Bn → Term Iri Lit Bn}
    (hσ : ∀ t ∈ H, ∀ x ∈ t.terms, σ x = x) (μ : Bn → Term Iri Lit Bn) :
    Graph.mapT σ (H.inst μ) = H.inst (fun b => σ (μ b)) := by
  simp only [Graph.inst, Graph.mapT, Set.image_image]
  apply Set.image_congr
  intro t ht
  rw [Triple.map_map]
  apply Triple.map_congr
  intro x hx
  cases x with
  | bnode b => rfl
  | iri a => simp only [Function.comp, Term.subst_iri]; exact hσ t ht _ hx
  | lit a => simp only [Function.comp, Term.subst_lit]; exact hσ t ht _ hx

variable (R : Regime Iri Lit Bn V)

/-- **Lemma 4 (Witness coordinate)**: if `μ₀(H) ⊆ X` with `X` over `G`'s terms and `V`, and
`ν₀ ∈ IMap N G`, then `ν₀ ∘ μ₀ ∈ IMap N H`. Stated for `X = cl_R(G) \ {⊥}`. -/
theorem witness_coordinate {G H : Graph Iri Lit Bn} (hA : Admissible N G H V)
    {μ₀ : Bn → Term Iri Lit Bn} (hμ₀ : H.inst μ₀ ⊆ R.clPos G) {ν₀} (hν₀ : ν₀ ∈ IMap N G) :
    (fun b => Term.subst ν₀ (μ₀ b)) ∈ IMap N H := by
  intro b hb
  obtain ⟨t, ht, hbt⟩ := hb
  have hmem : μ₀ b ∈ (R.clPos G).terms :=
    ⟨_, hμ₀ ⟨t, ht, rfl⟩, (Triple.mem_terms_map _ _).2 ⟨_, hbt, rfl⟩⟩
  rcases R.terms_clPos_subset G hmem with ⟨t', ht', hx⟩ | ⟨v, hv, hveq⟩
  · cases hμ : μ₀ b with
    | bnode b' =>
      rw [hμ] at hx
      simp only [hμ, Term.subst_bnode]
      exact hν₀ b' ⟨t', ht', hx⟩
    | iri a =>
      rw [hμ] at hx
      simp only [hμ, Term.subst_iri]
      exact hA.hG ⟨trivial, t', ht', hx⟩
    | lit a =>
      rw [hμ] at hx
      simp only [hμ, Term.subst_lit]
      exact hA.hG ⟨trivial, t', ht', hx⟩
  · show Term.subst ν₀ (μ₀ b) ∈ N
    rw [← hveq]
    simp only [Term.subst_iri]
    exact hA.hV v hv

/-- In the Herbrand model of `B_R`, a pair of ground graphs over `N` is a good implication
iff `Γ` is `R`-inconsistent or `Δ` meets `cl_R(Γ)`. -/
theorem Regime.mem_frame_iff {Γ Δ : Graph Iri Lit Bn} (hΓ : Γ ⊆ Lex N) (hΔ : Δ ⊆ Lex N) :
    (Γ, Δ) ∈ (R.base N).frame ↔ R.Inconsistent Γ ∨ (Δ ∩ R.clPos Γ).Nonempty :=
  ⟨(R.base N).rel_of_mem_frame hΓ hΔ, (R.base N).mem_frame_of_rel hΓ hΔ⟩

/-- **Lemma 7 (Witness characterization).** -/
theorem witness_characterization {G H : Graph Iri Lit Bn} (hA : Admissible N G H V) :
    (R.base N).herbrand.GEnt N G H ↔ R.Entails G H := by
  rw [Model.gEnt_iff]
  simp only [Base.herbrand_brG]
  constructor
  · -- only if
    intro h
    by_contra hne
    simp only [Regime.Entails, SimpleEntails, not_or, not_exists] at hne
    obtain ⟨hcons, hnowit⟩ := hne
    obtain ⟨νsk, σ, hνsk, hσ, hσG, hσH⟩ := skolemization hA
    set Γ : Graph Iri Lit Bn := G.inst νsk with hΓdef
    have hΓcons : ¬ R.Inconsistent Γ := by
      intro hi
      apply hcons
      have := R.inconsistent_map hσ hi
      rwa [hσG] at this
    have hSne : ∀ μ ∈ IMap N H, (H.inst μ \ R.clPos Γ).Nonempty := by
      intro μ _
      rw [Set.sdiff_nonempty]
      intro hsub
      apply hnowit (fun b => σ (μ b))
      rw [← Graph.mapT_inst_of_fixes hσH]
      calc Graph.mapT σ (H.inst μ) ⊆ Graph.mapT σ (R.clPos Γ) := Graph.mapT_mono _ hsub
        _ ⊆ R.clPos (Graph.mapT σ Γ) := R.clPos_map hσ Γ
        _ = R.clPos G := by rw [hΓdef, hσG]
    have hpair := h {νsk} (by simpa using hνsk) (Set.singleton_nonempty _)
      (fun μ => H.inst μ \ R.clPos Γ) (fun μ hμ => ⟨hSne μ hμ, Set.sdiff_subset⟩)
    rw [Set.biUnion_singleton] at hpair
    have hΓlex : Γ ⊆ Lex N := Graph.inst_subset_lex hA.hG hνsk
    have hΔlex : (⋃ μ ∈ IMap N H, (H.inst μ \ R.clPos Γ)) ⊆ Lex N := by
      intro t ht
      simp only [Set.mem_iUnion, exists_prop] at ht
      obtain ⟨μ, hμ, ht, -⟩ := ht
      exact Graph.inst_subset_lex hA.hH hμ ht
    rcases (R.mem_frame_iff hΓlex hΔlex).1 hpair with hi | ⟨t, ht, htc⟩
    · exact hΓcons hi
    · simp only [Set.mem_iUnion, exists_prop] at ht
      obtain ⟨μ, -, -, hnot⟩ := ht
      exact hnot htc
  · -- if
    intro h x hx hne S hS
    have hΓlex : (⋃ ν ∈ x, G.inst ν) ⊆ Lex N := by
      intro t ht
      simp only [Set.mem_iUnion, exists_prop] at ht
      obtain ⟨ν, hν, ht⟩ := ht
      exact Graph.inst_subset_lex hA.hG (hx hν) ht
    have hΔlex : (⋃ μ ∈ IMap N H, S μ) ⊆ Lex N := by
      intro t ht
      simp only [Set.mem_iUnion, exists_prop] at ht
      obtain ⟨μ, hμ, ht⟩ := ht
      exact Graph.inst_subset_lex hA.hH hμ ((hS μ hμ).2 ht)
    rw [R.mem_frame_iff hΓlex hΔlex]
    obtain ⟨ν₀, hν₀⟩ := hne
    have hsub : G.inst ν₀ ⊆ ⋃ ν ∈ x, G.inst ν := Set.subset_biUnion_of_mem (u := fun ν => G.inst ν) hν₀
    rcases h with hi | ⟨μ₀, hμ₀⟩
    · left
      exact R.inconsistent_mono hsub (R.inconsistent_map (fixesLV_subst V ν₀) hi)
    · right
      have hμ' := witness_coordinate R hA hμ₀ (hx hν₀)
      obtain ⟨b, hb⟩ := (hS _ hμ').1
      refine ⟨b, Set.mem_biUnion hμ' hb, ?_⟩
      have hb' := (hS _ hμ').2 hb
      rw [← Graph.inst_inst] at hb'
      have hchain : Graph.inst ν₀ (H.inst μ₀) ⊆ R.clPos (⋃ ν ∈ x, G.inst ν) :=
        calc Graph.inst ν₀ (H.inst μ₀) ⊆ Graph.inst ν₀ (R.clPos G) := Graph.inst_mono _ hμ₀
          _ ⊆ R.clPos (G.inst ν₀) := R.clPos_map (fixesLV_subst V ν₀) G
          _ ⊆ R.clPos (⋃ ν ∈ x, G.inst ν) := R.clPos_mono hsub
      exact hchain hb'

/-- **Proposition 2 (Incoherence recovery).** -/
theorem incoherence_recovery {G : Graph Iri Lit Bn} (hA : Admissible N G ∅ V) :
    (R.base N).herbrand.Incoherent N G ↔ R.Inconsistent G := by
  rw [Model.incoherent_iff]
  simp only [Base.herbrand_brG]
  constructor
  · intro h
    by_contra hcons
    obtain ⟨νsk, σ, hνsk, hσ, hσG, -⟩ := skolemization hA
    have hpair := h {νsk} (by simpa using hνsk) (Set.singleton_nonempty _)
    rw [Set.biUnion_singleton] at hpair
    have hΓlex : G.inst νsk ⊆ Lex N := Graph.inst_subset_lex hA.hG hνsk
    rcases (R.mem_frame_iff hΓlex (Set.empty_subset _)).1 hpair with hi | ⟨t, ht, -⟩
    · apply hcons
      have := R.inconsistent_map hσ hi
      rwa [hσG] at this
    · exact ht
  · intro hi x hx hne
    have hΓlex : (⋃ ν ∈ x, G.inst ν) ⊆ Lex N := by
      intro t ht
      simp only [Set.mem_iUnion, exists_prop] at ht
      obtain ⟨ν, hν, ht⟩ := ht
      exact Graph.inst_subset_lex hA.hG (hx hν) ht
    rw [R.mem_frame_iff hΓlex (Set.empty_subset _)]
    left
    obtain ⟨ν₀, hν₀⟩ := hne
    exact R.inconsistent_mono (Set.subset_biUnion_of_mem (u := fun ν => G.inst ν) hν₀)
      (R.inconsistent_map (fixesLV_subst V ν₀) hi)

/-- **Theorem 2 (Closure regimes).** Implication in the models fit for `B_R` is `R`-entailment. -/
theorem closure_regimes {G H : Graph Iri Lit Bn} (hA : Admissible N G H V) :
    FitEnt (R.base N) G H ↔ R.Entails G H :=
  (recovery (R.base N) hA.hG hA.hH).trans (witness_characterization R hA)

/-- **Corollary 1 (Simple RDF entailment).** -/
theorem simple_entailment_recovery {G H : Graph Iri Lit Bn}
    (hA : Admissible N G H (∅ : Set Iri)) :
    FitEnt ((emptyRegime Iri Lit Bn ∅).base N) G H ↔ SimpleEntails G H :=
  (closure_regimes _ hA).trans (emptyRegime_entails_iff ∅ G H)

/-- Corollary 1, second half, via Lemma 1. -/
theorem simple_entailment_recovery_std {G H : Graph Iri Lit Bn} (hG : G.Standard)
    (hA : Admissible N G H (∅ : Set Iri)) :
    FitEnt ((emptyRegime Iri Lit Bn ∅).base N) G H ↔ SimpleEntailsStd G H :=
  (simple_entailment_recovery hA).trans (simpleEntails_iff_std hG)

/-- Theorem 2's right-hand side does not mention `N`: the verdict is the same for every
admissible `N`. -/
theorem fitEnt_independent_of_N {N N' : Set (Term Iri Lit Bn)} {G H : Graph Iri Lit Bn}
    (hA : Admissible N G H V) (hA' : Admissible N' G H V) :
    FitEnt (R.base N) G H ↔ FitEnt (R.base N') G H := by
  rw [closure_regimes R hA, closure_regimes R hA']

end ISRDF
